### ISSUE TITLE
StreamStats vs. NLDI Watershed

### ISSUE THREAD

**Issue by USGSPMM3** [cheginit/pygeohydro#38]
I was compiling a list of projects/users for the StreamStats services and Dave Blodgett indicated you were using StreamStats. I see you've replaced StreamStats with NLDI services. I have a couple of additional pieces of information for you:
NLDI and StreamStats are working together to revise the NLDI delineation tools so they will delineate from a click point not just from the catchment.
The data processing steps and quality assurance work, as well as the underlying data in StreamStats, typically mean that delineations from StreamStats will be more accurate than from the NHDPlus datasets being queried in NLDI. For example, South Carolina data is based on lidar data, we're currently working on 3-meter lidar data in Nebraska. Thus, depending on the use, you may want to include the option of using StreamStats as well as NLDI.

Thanks!

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

**Comment by cheginit** [comment]
Thanks for providing this new information. Actually, I remember that I was comparing NLDI and StreamStats for getting basin geometry and noticed that there's noticeable difference between the two and since NLDI has some other interesting features I decided to make the switch. I will definitely revisit StreamStats and think about how it can best be implemented.

I will take a look at it and will let you know if I have any questions. Please feel free to let me know if you have any suggestions. I will will be implementing in [PyNHD](https://github.com/cheginit/pynhd) package.

**Comment by cheginit** [comment]
Considering that [streamstats](https://github.com/earthlab/streamstats) already exists, there's no point in adding this.
